pysmo/sac/sacheader.py, pysmo/sac/sacio.py
Also adjusted logic in sacfile class to match this.
=> Place SAC header fields in a separate descriptor class.

pysmo/core/sac/sacheader.py, pysmo/core/sac/sacio.py, tests/test_sacio.py
- kztime and kztime are printed in ISO format
- additional code cleanups
=> Add derived headers kztime and kzdate.

.travis.yml, pysmo/__init__.py, pysmo/core/__init__.py, pysmo/core/sac/__init__.py, pysmo/core/sac/sacheader.py, pysmo/core/sac/sacio.py, pysmo/core/sac/sacmeth.py, pysmo/tools/__init__.py, pysmo/tools/noise/peterson.py, setup.py
=> Remove py2

docs/source/conf.py, docs/source/developing.rst, docs/source/index.rst, docs/source/installation.rst
- Add development docs
- Update installation instructions to be the same as aimbat
=> Add development docs.

pyproject.toml, pysmo/core/sac/sacio.py, tests/test_sacio.py
It will allow to read a SAC file from memory, for example, if the file comes from a URL request, avoid to save it into a temporary file.
Added a test to check the read_data works.
=> Added two methods to sacio.SacIO: read_data and from_data

pyproject.toml, pysmo/core/sac/sacheader.py, pysmo/core/sac/sacheader.yml, pysmo/core/sac/sacio.py, tests/test_sacio.py
Stores sac header values in the SacIO object instead of in a dictionary residing in the descriptors.
=> New sacheaders

.readthedocs.yml, docs/requirements.txt
Fix building documentation on readthedocs
=> Fix documentation

.github/workflows/build.yml, pysmo/core/sac/sacheader.py, tests/test_sac_protocols.py
----
:books: Documentation preview :books:: https://pysmo--60.org.readthedocs.build/en/60/
=> Sac station

pysmo/core/sac/sac.py, tests/test_sac_protocols.py
----
:books: Documentation preview :books:: https://pysmo--61.org.readthedocs.build/en/61/
=> Add tests for event protocol

Makefile
Incorporate @Omkar-Ranadive 's changes to the Makefile 
----
:books: Documentation preview :books:: https://pysmo--72.org.readthedocs.build/en/72/
=> Edit Makefile to run also on windows

pysmo/__init__.py, pysmo/classes/mini.py, pysmo/classes/sac.py, pysmo/types.py, tests/test_mini_protocols.py
Fixes #64 
----
:books: Documentation preview :books:: https://pysmo--78.org.readthedocs.build/en/78/
=> Add Mini classes

docs/source/classes.md, docs/source/installation.md, pysmo/classes/mini.py, pysmo/classes/sac.py
----
:books: Documentation preview :books:: https://pysmo--84.org.readthedocs.build/en/84/
=> Classes documentation

docs/source/functions.md, pysmo/functions/azdist.py
----
:books: Documentation preview :books:: https://pysmo--85.org.readthedocs.build/en/85/
=> Add docs for functions

docs/source/classes.md, pysmo/classes/mini.py
----
:books: Documentation preview :books:: https://pysmo--87.org.readthedocs.build/en/87/
=> add inherited attributes to SAC documentation

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/postAttachCommand.sh, .gitattributes
----
:books: Documentation preview :books:: https://pysmo--93.org.readthedocs.build/en/93/
=> Update Devcontainer Config

.github/workflows/run-tests.yml, .gitignore, Makefile, poetry.lock, pyproject.toml, setup.cfg, tox.ini
fixes #75 
----
:books: Documentation preview :books:: https://pysmo--94.org.readthedocs.build/en/94/
=> Test with tox and add windows to matrix

tox.ini
----
:books: Documentation preview :books:: https://pysmo--96.org.readthedocs.build/en/96/
=> Change tox config

.github/workflows/build.yml
----
:books: Documentation preview :books:: https://pysmo--104.org.readthedocs.build/en/104/
=> Modify build workflow to run on new tags

.github/workflows/run-tests.yml, pyproject.toml, pysmo/classes/sac.py, pysmo/io/sacio/sacio.py, tests/classes/test_sac.py, tests/functions/test_azdist.py, tox.ini
----
:books: Documentation preview :books:: https://pysmo--107.org.readthedocs.build/en/107/
=> Add a bit more testing

changelog.md, pysmo/classes/sac.py
----
:books: Documentation preview :books:: https://pysmo--113.org.readthedocs.build/en/113/
=> refactor: move SAC helper classes inside SAC class

docs/snippets/functions.py, pysmo/classes/mini.py, pysmo/functions.py, pysmo/lib/functions.py, tests/classes/test_mini.py, tests/conftest.py
----
:books: Documentation preview :books:: https://pysmo--117.org.readthedocs.build/en/117/
=> feat: add methods corresponding to functions to mini class

pysmo/__init__.py, pysmo/classes/mini.py, pysmo/classes/sac.py, pysmo/types.py, tests/classes/test_mini.py
----
:books: Documentation preview :books:: https://pysmo--119.org.readthedocs.build/en/119/
=> feat: add Event type and MiniEvent class

changelog.md, pysmo/classes/mini.py, pysmo/classes/sac.py, tests/classes/test_sac.py
----
:books: Documentation preview :books:: https://pysmo--120.org.readthedocs.build/en/120/
=> fix: add event time to SacEvent

pysmo/classes/mini.py, pysmo/classes/sac.py, pysmo/lib/io/sacio.py
----
:books: Documentation preview :books:: https://pysmo--122.org.readthedocs.build/en/122/
=> refactor: use pydantic dataclass for mini classes

docs/snippets/test_functions.py, pyproject.toml, pysmo/__init__.py, pysmo/classes/mini.py, pysmo/functions.py, pysmo/lib/io/sacio.py, pysmo/tools/signal.py, tests/classes/mini/test_mini_seismogram.py, tests/functions/test_functions.py, tests/lib/io/test_sacio.py
----
:books: Documentation preview :books:: https://pysmo--124.org.readthedocs.build/en/124/
=> refactor: change clone_to_miniseismogram function to classmethod

docs/first-steps/index.md
----
:books: Documentation preview :books:: https://pysmo--125.org.readthedocs.build/en/125/
=> docs: update "not-so-fast" section

Makefile, poetry.lock, pyproject.toml, pysmo/classes/sac.py, tox.ini
----
:books: Documentation preview :books:: https://pysmo--128.org.readthedocs.build/en/128/
=> test: lint with ruff instead of flake8

docs/developing/index.md
----
:books: Documentation preview :books:: https://pysmo--129.org.readthedocs.build/en/129/
=> docs: be a bit more specific in 'rules of the land'

Makefile, poetry.lock, pyproject.toml, tox.ini
----
:books: Documentation preview :books:: https://pysmo--130.org.readthedocs.build/en/130/
=> test: check tutorial notebook runs error free

.github/workflows/run-tests.yml, tox.ini
----
:books: Documentation preview :books:: https://pysmo--131.org.readthedocs.build/en/131/
=> ci: combine coverage results before uploading and add osx

docs/examples/tools/noise/peterson.py, docs/first-steps/tutorial.ipynb, docs/snippets/functions.py, docs/snippets/test_functions.py, docs/user-guide/types.md, pysmo/classes/mini.py, pysmo/classes/sac.py, pysmo/functions.py, pysmo/lib/defaults.py, pysmo/lib/functions.py, pysmo/tools/noise.py, pysmo/tools/signal.py, pysmo/types.py, tests/classes/mini/test_mini_seismogram.py, tests/classes/test_sac.py, tests/functions/conftest.py, tests/functions/test_functions.py, tests/tools/test_noise.py, tests/tools/test_signal.py
should have either been sampling_interval or delta in the first place.
----
:books: Documentation preview :books:: https://pysmo--137.org.readthedocs.build/en/137/
=> refactor: rename sampling_rate to delta.

.devcontainer/Dockerfile, .devcontainer/devcontainer.json
----
:books: Documentation preview :books:: https://pysmo--143.org.readthedocs.build/en/143/
=> chore: don't install pandoc, don't run post attach commands

flake.lock, flake.nix, poetry.lock, pyproject.toml
----
📚 Documentation preview 📚: https://pysmo--161.org.readthedocs.build/en/161/
=> chore: update dependencies

docs/user-guide/classes/sac.md, flake.lock, poetry.lock, pysmo/classes/sac.py, tests/classes/test_sac.py
----
📚 Documentation preview 📚: https://pysmo--163.org.readthedocs.build/en/163/
=> (feat) Add sac timestamps

.github/workflows/run-tests.yml
----
📚 Documentation preview 📚: https://pysmo--170.org.readthedocs.build/en/170/
=> chore: upload hidden files as artifacts for codecov ci step

.github/workflows/run-tests.yml, .gitignore, tox.ini
----
📚 Documentation preview 📚: https://pysmo--171.org.readthedocs.build/en/171/
=> tests: add codecov token to workflow

pysmo/classes/mini.py, tests/classes/mini/test_mini_station.py
----
📚 Documentation preview 📚: https://pysmo--173.org.readthedocs.build/en/173/
=> feat: remove converters from mini classes

.github/workflows/gh-pages.yml
----
📚 Documentation preview 📚: https://pysmo--175.org.readthedocs.build/en/175/
=> ci: add gh-pages workflow

.github/workflows/build.yml, .github/workflows/run-tests.yml, .gitignore, flake.lock, flake.nix, mkdocs.yml, poetry.lock, pyproject.toml, tox.ini
----
📚 Documentation preview 📚: https://pysmo--176.org.readthedocs.build/en/176/
=> chore: Tweaks to docs and add python 3.13 to matrix

docs/user-guide/functions.md, flake.lock, mkdocs.yml, poetry.lock, pyproject.toml, pysmo/_lib/decorators.py, pysmo/functions/__init__.py, pysmo/functions/_seismogram.py, pysmo/tools/signal.py, tests/functions/test_functions.py, tests/tools/test_signal.py
----
📚 Documentation preview 📚: https://pysmo--190.org.readthedocs.build/en/190/
=> feat: add clone arg to functions

docs/developing/contributing.md, docs/developing/developing.md, docs/developing/index.md, docs/first-steps/index.md, docs/user-guide/classes.md, docs/user-guide/in-the-box.md, docs/user-guide/index.md, docs/user-guide/types.md, mkdocs.yml
----
📚 Documentation preview 📚: https://pysmo--208.org.readthedocs.build/en/208/
=> docs: add a small paragraph on how to use the documentation

mkdocs.yml, pyproject.toml, pysmo/lib/io/_sacio/sacio.py, tests/lib/io/test_sacio.py, uv.lock
----
📚 Documentation preview 📚: https://pysmo--209.org.readthedocs.build/en/209/
=> refactor: use httpx instead of requests

pysmo/tools/iccs/_functions.py
----
📚 Documentation preview 📚: https://pysmo--219.org.readthedocs.build/en/219/
=> fix: add key to sorted call

pysmo/tools/iccs/_functions.py
----
📚 Documentation preview 📚: https://pysmo--223.org.readthedocs.build/en/223/
=> fix: allow selecing index 0

docs/api/index.md, pysmo/__init__.py, pysmo/_types/_station.py, pysmo/classes/_sac.py, pysmo/tools/iccs/_functions.py, pysmo/tools/iccs/_iccs.py, tests/classes/mini/test_mini_station.py, tests/classes/test_sac.py, tests/conftest.py
----
📚 Documentation preview 📚: https://pysmo--225.org.readthedocs.build/en/225/
=> feat: add channel and location to station type
